// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8maNMSeQiYNsarxXKstypTgfrB7Clu-0',
    appId: '1:871745638660:web:9faddaee66b4ecddd50051',
    messagingSenderId: '871745638660',
    projectId: 'talkiee-app-c7156',
    authDomain: 'talkiee-app-c7156.firebaseapp.com',
    storageBucket: 'talkiee-app-c7156.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANhmGy5nBfiGQM16ppvYQIRf_tDYx6qzI',
    appId: '1:871745638660:android:d5739a98c5f38681d50051',
    messagingSenderId: '871745638660',
    projectId: 'talkiee-app-c7156',
    storageBucket: 'talkiee-app-c7156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSZFPA7dy0Xi3az16SdfvH0iAuo4HRwQ',
    appId: '1:871745638660:ios:5603174b5e1575e9d50051',
    messagingSenderId: '871745638660',
    projectId: 'talkiee-app-c7156',
    storageBucket: 'talkiee-app-c7156.firebasestorage.app',
    iosBundleId: 'com.example.talkieeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8maNMSeQiYNsarxXKstypTgfrB7Clu-0',
    appId: '1:871745638660:web:7ee953c9f503f0d6d50051',
    messagingSenderId: '871745638660',
    projectId: 'talkiee-app-c7156',
    authDomain: 'talkiee-app-c7156.firebaseapp.com',
    storageBucket: 'talkiee-app-c7156.firebasestorage.app',
  );
}
